In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import  LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

In [2]:
data = pd.read_csv('/Users/alejandropalacios/Desktop/Ironhack/Data Analytics Bootcamp/Advanced Data Analysis Techniques/Project/F1-Grand-Prix-Predictor/Data Manipulation/Modeling/Modeled Databases/driver_change_dataset.csv')

In [3]:
# We must get dummies for the categorical variables dataset in order to properly run our Model.

# Moreover, the following Variables will be used based on our results (in reverse order of Predictive Power):

"""

- nationality
- grid	
- qualifying_time
- constructor
- constructor_wins
- constructor_standings_pos
- driver

"""

df_woeiv = data[['season','nationality','grid','qualifying_time','constructor','constructor_wins','constructor_standings_pos','driver','change_drivers']]

df_dum = pd.get_dummies(df_woeiv, columns = ['constructor','driver','nationality'] )

for col in df_dum.columns:
    if 'constructor' in col and df_dum[col].sum() < 140:
        df_dum.drop(col, axis = 1, inplace = True)
    
    elif 'driver' in col and df_dum[col].sum() < 140:
        df_dum.drop(col, axis = 1, inplace = True)

    elif 'nationality' in col and df_dum[col].sum() < 140:
        df_dum.drop(col, axis = 1, inplace = True)

    else:
        pass

df_dum.to_csv('/Users/alejandropalacios/Desktop/Ironhack/Data Analytics Bootcamp/Advanced Data Analysis Techniques/Project/F1-Grand-Prix-Predictor/Data Manipulation/Modeling/Modeled Databases/driver_change_dummies_dataset.csv', index = False)

In [4]:
df = pd.read_csv('/Users/alejandropalacios/Desktop/Ironhack/Data Analytics Bootcamp/Advanced Data Analysis Techniques/Project/F1-Grand-Prix-Predictor/Data Manipulation/Modeling/Modeled Databases/driver_change_dummies_dataset.csv')

In [5]:
df = df[[c for c in df if c not in ['change_drivers']] + ['change_drivers']]

In [6]:
# Train the Model

train = df[df.season < 2019]
test = df[df.season == 2019]

X_train = train.drop('change_drivers',axis=1)
y_train = train.change_drivers

X_test = test.drop('change_drivers',axis=1)
y_test = test.change_drivers

In [7]:
# Logistic Regression

logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test,y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))



Confusion Matrix:
 [[379   0]
 [ 13   0]]

Model Accuracy Score:
 0.9668367346938775

Model Precision Score:
 0.0

Model Recall Score:
 0.0


In [8]:
# Decision Tree Classifier

tree_model = DecisionTreeClassifier()
tree_model.fit(X_train,y_train)
y_pred = tree_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[376   3]
 [ 11   2]]

Model Accuracy Score:
 0.9642857142857143

Model Precision Score:
 0.4

Model Recall Score:
 0.15384615384615385


In [9]:
# Linear Discriminant Analysis

linear_model = LinearDiscriminantAnalysis()
linear_model.fit(X_train, y_train)
y_pred = linear_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[378   1]
 [  8   5]]

Model Accuracy Score:
 0.9770408163265306

Model Precision Score:
 0.8333333333333334

Model Recall Score:
 0.38461538461538464


In [10]:
# Random Forest Classifier

forest_model = RandomForestClassifier(n_jobs=2, random_state=0)
forest_model.fit(X_train, y_train)
y_pred = forest_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[379   0]
 [ 11   2]]

Model Accuracy Score:
 0.9719387755102041

Model Precision Score:
 1.0

Model Recall Score:
 0.15384615384615385


In [11]:
# Support Vector Classifier

svc_model = SVC()
svc_model.fit(X_train, y_train)
y_pred = svc_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[379   0]
 [ 13   0]]

Model Accuracy Score:
 0.9668367346938775

Model Precision Score:
 0.0

Model Recall Score:
 0.0


In [12]:
# K Neighbors Classifier

knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
y_pred = knn_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[379   0]
 [ 10   3]]

Model Accuracy Score:
 0.9744897959183674

Model Precision Score:
 1.0

Model Recall Score:
 0.23076923076923078
