In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import  LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

In [2]:
df = pd.read_csv('/Users/alejandropalacios/Desktop/Ironhack/Data Analytics Bootcamp/Advanced Data Analysis Techniques/Project/F1-Grand-Prix-Predictor/Data Manipulation/Modeling/Modeled Databases/team_change_dummies_dataset.csv')


# Moreover, the following Variables will be used based on our results (in order of Predictive Power):

"""

- constructor_standings_pos
- constructor_wins
- driver
- qualifying_time
- constructor
- podium

"""

'\n\n- constructor_standings_pos\n- constructor_wins\n- driver\n- qualifying_time\n- constructor\n- podium\n\n'

In [3]:
df = df[[c for c in df if c not in ['change_teams']] + ['change_teams']]

In [4]:
# Train the Model

train = df[df.season < 2019]
test = df[df.season == 2019]

X_train = train.drop('change_teams',axis=1)
y_train = train.change_teams

X_test = test.drop('change_teams',axis=1)
y_test = test.change_teams

In [5]:
# Logistic Regression

logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test,y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))



Confusion Matrix:
 [[370   0]
 [  2  20]]

Model Accuracy Score:
 0.9948979591836735

Model Precision Score:
 1.0

Model Recall Score:
 0.9090909090909091


In [6]:
# Decision Tree Classifier

tree_model = DecisionTreeClassifier()
tree_model.fit(X_train,y_train)
y_pred = tree_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[364   6]
 [  2  20]]

Model Accuracy Score:
 0.9795918367346939

Model Precision Score:
 0.7692307692307693

Model Recall Score:
 0.9090909090909091


In [7]:
# Linear Discriminant Analysis

linear_model = LinearDiscriminantAnalysis()
linear_model.fit(X_train, y_train)
y_pred = linear_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[365   5]
 [  3  19]]

Model Accuracy Score:
 0.9795918367346939

Model Precision Score:
 0.7916666666666666

Model Recall Score:
 0.8636363636363636


In [8]:
# Random Forest Classifier

forest_model = RandomForestClassifier(n_jobs=2, random_state=0)
forest_model.fit(X_train, y_train)
y_pred = forest_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[370   0]
 [  2  20]]

Model Accuracy Score:
 0.9948979591836735

Model Precision Score:
 1.0

Model Recall Score:
 0.9090909090909091


In [9]:
# Support Vector Classifier

svc_model = SVC()
svc_model.fit(X_train, y_train)
y_pred = svc_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[370   0]
 [ 22   0]]

Model Accuracy Score:
 0.9438775510204082

Model Precision Score:
 0.0

Model Recall Score:
 0.0


In [10]:
# K Neighbors Classifier

knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
y_pred = knn_model.predict(X_test)

print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nModel Accuracy Score:\n",accuracy_score(y_test, y_pred))
print("\nModel Precision Score:\n",precision_score(y_test,y_pred))
print("\nModel Recall Score:\n",recall_score(y_test,y_pred))


Confusion Matrix:
 [[370   0]
 [  2  20]]

Model Accuracy Score:
 0.9948979591836735

Model Precision Score:
 1.0

Model Recall Score:
 0.9090909090909091
